### ISSUE TITLE
App crash if auto logging enabled + logging on button was pressed directly after start

### ISSUE THREAD

**Issue by CHEF-KOCH** [pragma-/networklog#13]
If the auto logging option on startup is enabled + you press the log _loggin on_ button directly after app startup it lets the app crash imminently. That may have todo with the fact that it requests SU on startup. 

Network Log version tested: 2.24.2/2.25.0
OS: Any (tested with 4.4.4 - M)
Log: I not provide one since this is an major issue but let me know if you really need one.
IPTables used: Build-in (1.4.21)
nflog/grep: latest 1.11 / 1.2.5
SU: 2.49 
Other changed settings: DNS/portnames activated, logging behind a firewall, Foreground activity and stop the protocol after the app was closed

Thanks for fixing and of course the good work.

**Comment by pyc0de** [comment]
Any news on this issue?
App is useless on CM13.

logcat:
I/ActivityManager( 2096): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.googlecode.networklog/.NetworkLog bnds=[400,75][600,380] (has extras)} from uid 10021 on display 0
I/ActivityManager( 2096): Start proc 21298:com.googlecode.networklog/u0a139 for activity com.googlecode.networklog/.NetworkLog
W/System  (21298): ClassLoader referenced unknown path: /data/app/com.googlecode.networklog-1/lib/arm
W/XPrivacy(21298): Hooking package=com.googlecode.networklog
W/NetworkLog(21298): loadEntriesFromFile
W/NetworkLog(21298): java.io.FileNotFoundException: /storage/emulated/0/networklog.txt: open failed: ENOENT (No such file or directory)
W/NetworkLog(21298): 	at libcore.io.IoBridge.open(IoBridge.java:452)
W/NetworkLog(21298): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/NetworkLog(21298): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:738)
W/NetworkLog(21298): 	at libcore.io.IoBridge.open(<Xposed>)
W/NetworkLog(21298): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
W/NetworkLog(21298): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
W/NetworkLog(21298): 	at com.googlecode.networklog.LogfileLoader.openLogfile(LogfileLoader.java:48)
W/NetworkLog(21298): 	at com.googlecode.networklog.HistoryLoader.loadEntriesFromFile(HistoryLoader.java:63)
W/NetworkLog(21298): 	at com.googlecode.networklog.NetworkLog$InitRunner.run(NetworkLog.java:242)
W/NetworkLog(21298): 	at java.lang.Thread.run(Thread.java:818)
W/NetworkLog(21298): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/NetworkLog(21298): 	at libcore.io.Posix.open(Native Method)
W/NetworkLog(21298): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
W/NetworkLog(21298): 	at libcore.io.IoBridge.open(IoBridge.java:438)
W/NetworkLog(21298): 	... 9 more
I/ActivityManager( 2096): Displayed com.googlecode.networklog/.NetworkLog: +1s426ms
E/AndroidRuntime(21298): Process: com.googlecode.networklog, PID: 21298
E/AndroidRuntime(21298): java.lang.NullPointerException: Attempt to read from field 'int com.googlecode.networklog.ApplicationsTracker$AppEntry.uid' on a null object reference
E/AndroidRuntime(21298): 	at com.googlecode.networklog.Iptables.addRules(Iptables.java:128)
E/AndroidRuntime(21298): 	at com.googlecode.networklog.NetworkLogService.startLogging(NetworkLogService.java:953)
E/AndroidRuntime(21298): 	at com.googlecode.networklog.NetworkLogService$3.run(NetworkLogService.java:394)
W/ActivityManager( 2096):   Force finishing activity com.googlecode.networklog/.NetworkLog
E/ActivityThread(21298): Activity com.googlecode.networklog.NetworkLog has leaked IntentReceiver com.googlecode.networklog.ApplicationsTracker$PackageIntentReceiver@dfff8bc that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(21298): android.app.IntentReceiverLeaked: Activity com.googlecode.networklog.NetworkLog has leaked IntentReceiver com.googlecode.networklog.ApplicationsTracker$PackageIntentReceiver@dfff8bc that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(21298): 	at com.googlecode.networklog.ApplicationsTracker$PackageIntentReceiver.<init>(ApplicationsTracker.java:185)
E/ActivityThread(21298): 	at com.googlecode.networklog.ApplicationsTracker.startWatchingPackages(ApplicationsTracker.java:237)
E/ActivityThread(21298): 	at com.googlecode.networklog.ApplicationsTracker.getInstalledApps(ApplicationsTracker.java:323)
E/ActivityThread(21298): 	at com.googlecode.networklog.NetworkLog$InitRunner.run(NetworkLog.java:236)
I/ActivityManager( 2096): Process com.googlecode.networklog (pid 21298) has died
W/ActivityManager( 2096): Scheduling restart of crashed service com.googlecode.networklog/.NetworkLogService in 1000ms
I/ActivityManager( 2096): Start proc 21446:com.googlecode.networklog/u0a139 for service com.googlecode.networklog/.NetworkLogService
W/System  (21446): ClassLoader referenced unknown path: /data/app/com.googlecode.networklog-1/lib/arm
W/XPrivacy(21446): Hooking package=com.googlecode.networklog
E/AndroidRuntime(21446): Process: com.googlecode.networklog, PID: 21446
E/AndroidRuntime(21446): java.lang.NullPointerException: Attempt to read from field 'int com.googlecode.networklog.ApplicationsTracker$AppEntry.uid' on a null object reference
E/AndroidRuntime(21446): 	at com.googlecode.networklog.Iptables.addRules(Iptables.java:128)
E/AndroidRuntime(21446): 	at com.googlecode.networklog.NetworkLogService.startLogging(NetworkLogService.java:953)
E/AndroidRuntime(21446): 	at com.googlecode.networklog.NetworkLogService$3.run(NetworkLogService.java:394)
I/ActivityManager( 2096): Process com.googlecode.networklog (pid 21446) has died
W/ActivityManager( 2096): Service crashed 2 times, stopping: ServiceRecord{f9eaeb5 u0 com.googlecode.networklog/.NetworkLogService}

**Comment by pyc0de** [comment]
Solved.
Delete app data and restart.
